[package]
name = "wayland-client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "wayland_test"
path = "src/main.rs"

[dependencies]
bitflags = '2.9'
rustix = '1.0'
thiserror = '2.0'

wayland-core = { version = '0.1', path = '../wayland-core/' }
wayland-scanner = { version = '0.1', path = '../wayland-scanner/' }
